image: gitpod/workspace-java-17

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: docker-compose up

# Learn more https://www.gitpod.io/docs/config-ports
ports:
  - name: Specify your preferences - Web App
    port: 8000
    onOpen: open-browser

# Learn More https://www.gitpod.io/docs/ides-and-editors/vscode-extensions#vs-code-extensions
vscode:
  extensions:
    - vscjava.vscode-java-pack
